<a href="https://colab.research.google.com/github/SSaratKS/Learning_PyTorch_Udemy_Course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


## About NVIDIA GPU
To check the GPU use command,

```
!nvidia-smi
```

Note:
Change runtime type in menu to GPU and rerun the import library installations to run the commands

In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.0+cu116


## Tensors Intro

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],[7,5]])
MATRIX

tensor([[7, 8],
        [7, 5]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 11, 12]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 11, 12]])

In [18]:
TENSOR[0,0]

tensor([1, 2, 3])

In [19]:
TENSOR[0,1,0]

tensor(3)

### Random tensors

why random tensors?

Random tensors used initially during machine learning for neural networks to learn and adjust the numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `


In [20]:
# Create a random tensor of size(3,4)

random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.8439, 0.4471, 0.3962, 0.7673],
         [0.1794, 0.3801, 0.6005, 0.7436],
         [0.8666, 0.8687, 0.1717, 0.5427]]])

In [21]:
random_tensor.ndim

3

In [22]:
# Create a random tensot with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
torch.rand(size=(3,3))

tensor([[0.1823, 0.9746, 0.9989],
        [0.8522, 0.1435, 0.4905],
        [0.3593, 0.3377, 0.2578]])

# Zeros and Ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [26]:
# Create a tensor of all zeros
ones = torch.ones(size=(2,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [27]:
ones.dtype # default datatype

torch.float32

In [28]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [29]:
# Use torch.range()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
torch.__version__

'1.13.0+cu116'

In [31]:
torch.arange(start = 0, end = 100, step = 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [32]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [33]:
# Float 32 tensor 