<a href="https://colab.research.google.com/github/SSaratKS/Learning_PyTorch_Udemy_Course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


## About NVIDIA GPU
To check the GPU use command,

```
!nvidia-smi
```

Note:
Change runtime type in menu to GPU and rerun the import library installations to run the commands

In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu116


## Tensors Intro

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],[7,5]])
MATRIX

tensor([[7, 8],
        [7, 5]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 11, 12]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 11, 12]])

In [18]:
TENSOR[0,0]

tensor([1, 2, 3])

In [19]:
TENSOR[0,1,0]

tensor(3)

### Random tensors

why random tensors?

Random tensors used initially during machine learning for neural networks to learn and adjust the numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `
